### ISSUE TITLE
你好，有关RulerView请教两个问题！

### ISSUE THREAD

**Issue by busfool** [yjwfn/RulerView#1]
第一个演示图上是不是有一个当前滑到的位置的指示标？这个在代码里好像没体现，请问在哪里呀

第二个如何获得松开手之后滑动的数据呢？rulerview的OnScaleListener onScaleChanged 好像在手滑动过程中一直会调用

非常感谢！

**Comment by yjwfn** [comment]
中间的位置指示符是另外的一个控件不是RulerView自带的。只在松开手的时候回调值里面没有实现，需要修改onTouchEvent的事件处理流程。
